name: Docker Build
on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: srzzumix/docker-luau:latest
      # - name: Push to version tag
      #   env:
      #     DOCKER_TAG: latest
      #     IMAGE_NAME: srzzumix/docker-luau:latest
      #     DOCKER_REPO: srzzumix/docker-luau
      #   run: |
      #     ./hooks/post_push
            
